drop table config if exists;
create table config(
	id bigint generated by default as identity,
	cron varchar(40),
	primary key(id)
);
insert into config(id,cron) values(1,'0 0/2 * * * ?'); -- 每2分钟执行一次定时任务